---
- hosts: all
  become: yes
  tasks:
      - name:  install java openjdk 8 on ubuntu 20.04
        apt:
            name: openjdk-8-jre
            state: present
        when: ansible_os_family == "Debian"


      - name: install java openjdk 8 on RedHat
        yum:
            name: java-1.8.0-openjdk
            state: present
        when: ansible_os_family == "RedHat"
